### ISSUE TITLE
Adding multiple left columns

### ISSUE THREAD

**Issue by dtdibaba** [neilstats/ckbplotr#17]
Hello:

I tried to add experimental event, experimental total N, control event and control N like in the meta package but even with the first two, the numbers overlap. I also tried to add color but it did not add.
Am I missing something?

**Comment by neilstats** [comment]
If you're using the col.left argument to add columns with the make_forest_plot function, then you also need to specify col.left.space (a numeric vector) as the gaps between the columns and the plot.
