### ISSUE TITLE
Examples for make_forest_plot

### ISSUE THREAD

**Issue by akhst7** [neilstats/ckbplotr#47]
Can you put code samples of the make_forest_plot ? 

Thanks.

**Comment by neilstats** [comment]
There are some examples in the 'Making forest plots' vignette, for example: [https://neilstats.github.io/ckbplotr/articles/make_forest_plot.html#forest-plot-with-row-labels](https://neilstats.github.io/ckbplotr/articles/make_forest_plot.html#forest-plot-with-row-labels)

I plan to add more examples, demonstrating all the features of make_forest_plot(), soon.

**Comment by akhst7** [comment]
Ok, Thanks.
